/*
 * This C++ source file was generated by the Gradle 'init' task.
 */

#include "app.h"
#define CATCH_CONFIG_MAIN  // This tells Catch to provide a main() - only do this in one cpp file
#include "catch.hpp"

//int main() {
//    app_using_catch::Greeter greeter;
//    assert(greeter.greeting().compare("Hello, World!") == 0);
//    return 0;
//}

TEST_CASE( "Factorials are computed", "[factorial]" ) {
    app_using_catch::Greeter greeter;
    REQUIRE( greeter.greeting().compare("Hello, World!") == 0 );
}